# Generated by Django 3.2.12 on 2023-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_postvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvote',
            old_name='post_id',
            new_name='post',
        ),
    ]
