# Generated by Django 3.2.12 on 2023-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_rename_post_id_postvote_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
    ]
