# Generated by Django 3.2.12 on 2023-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, to='crud.IpAddress'),
        ),
    ]
